#!/bin/sh

set -e

if [ "$1" = configure ]; then
    getent group sentrypeer >/dev/null 2>&1 || addgroup --system sentrypeer
    getent passwd sentrypeer >/dev/null 2>&1 ||
	adduser --system --home /var/lib/sentrypeer --no-create-home \
		--disabled-password --ingroup sentrypeer sentrypeer

    if [ -z "$2" ]; then
	mkdir -p /var/lib/sentrypeer
	chown root:sentrypeer /var/lib/sentrypeer
	chmod 775 /var/lib/sentrypeer
    fi
fi

#DEBHELPER#

exit 0

